###
GET http://localhost:5092

###
GET http://localhost:5092/api/produto/listar

###
POST http://localhost:5092/api/produto/cadastrar
Content-Type: application/json

{
    "nome": "Geladeira Bolada",
    "preco": 16.70,
    "quantidade": 2
}

###
GET http://localhost:5092/api/produto/buscar/